#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_mp2 - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/bitcoin.
Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.
Edit the BITCOIN_CLI setting to specify the location of bitcoin-cli.

=head1 NOTES

Uses env.BITCOIN_CLI and env.BITCOIN_DATADIR in /etc/munin/plugin-conf.d/bitcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind memory pool'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category bitcoind'
	echo 'bytes.label bytes'
	echo 'bytes.type GAUGE'
	echo 'bytes.max 1000000000'
	echo 'usage.label usage'
	echo 'usage.type GAUGE'
	echo 'usage.max 1000000000'
	exit 0
fi

# ${BITCOIN_CLI} getmempoolinfo
#{
#  "size": 11853,
#  "bytes": 45560692,
#  "usage": 89999136,
#  "maxmempool": 300000000,
#  "mempoolminfee": 0.00000000
#}

TFILE=/tmp/munin-bitcoin-mp2-$$
${BITCOIN_CLI} -datadir=$BITCOIN_DATADIR getmempoolinfo > $TFILE

echo "bytes.value `grep bytes $TFILE | grep -o '[0-9]*'`"
echo "usage.value `grep usage $TFILE | grep -o '[0-9]*'`"

rm $TFILE
