#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_ticker_bch - Plugin to monitor bcash tickers.

=head1 CONFIGURATION

No configuration.

=head1 NOTES

Uses python3.

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'multigraph bch_btc'
	echo 'graph_title bcash tickers - btc'
	echo 'graph_args --base 1000'
	#echo 'graph_scale no'
	echo 'graph_vlabel BTC'
	echo 'graph_category bitcoind'
	echo 'cexio_btc.label cex.io'
	echo 'coinmarketcap_btc.label coinmarketcap.com'
	echo 'hitbtc_btc.label hitbtc.com'
	echo 'kraken_btc.label kraken.com'
	echo 'shapeshift_btc.label shapeshift.io'

	echo 'multigraph bch_usd'
	echo 'graph_title bcash tickers - usd'
	echo 'graph_args --base 1000'
	echo 'graph_scale no'
	echo 'graph_vlabel USD'
	echo 'graph_category bitcoind'
	echo 'cexio_usd.label cex.io'
	echo 'coinmarketcap_usd.label coinmarketcap.com'
	echo 'hitbtc_usd.label hitbtc.com'
	echo 'kraken_usd.label kraken.com'

	echo 'multigraph bch_cny'
	echo 'graph_title bcash tickers - cny'
	echo 'graph_args --base 1000'
	echo 'graph_scale no'
	echo 'graph_vlabel CNY'
	echo 'graph_category bitcoind'
	echo 'coinmarketcap_cny.label coinmarketcap.com'
	echo 'chbtc_cny.label chbtc.com'
	exit 0
fi

coinmarketcap=`curl -m 10 -L -s 'https://api.coinmarketcap.com/v1/ticker/bitcoin-cash/?convert=CNY' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("#coinmarketcap_btc.value " + j[0]["price_btc"])
 print("#coinmarketcap_usd.value " + j[0]["price_usd"])
 print("#coinmarketcap_cny.value " + j[0]["price_cny"])
except:
 pass'`

cexio=`curl -m 10 -L -s 'https://cex.io/api/tickers/USD/BCH/BTC' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("#cexio_usd.value " + str(j["data"][1]["last"]))
 print("#cexio_btc.value " + str(j["data"][3]["last"]))
except:
 pass'`

hitbtc=`curl -m 10 -L -s 'https://api.hitbtc.com/api/1/public/ticker' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("#hitbtc_btc.value " + str(j["BCCBTC"]["last"]))
 print("#hitbtc_usd.value " + str(j["BCCUSD"]["last"]))
except:
 pass'`

kraken=`curl -m 10 -L -s 'https://api.kraken.com/0/public/Ticker?pair=BCHUSD,BCHXBT' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("#kraken_usd.value " + str(j["result"]["BCHUSD"]["c"][0]))
 print("#kraken_btc.value " + str(j["result"]["BCHXBT"]["c"][0]))
except:
 pass'`

echo multigraph bch_btc
echo $cexio | tr '#' '\n' | grep btc
echo $coinmarketcap | tr '#' '\n' | grep btc

echo $hitbtc  | tr '#' '\n' | grep _btc
echo $kraken | tr '#' '\n' | grep btc

curl -m 10 -L -s 'https://shapeshift.io/marketinfo/bch_btc' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("shapeshift_btc.value " + str(j["rate"]))
except:
 pass'

echo multigraph bch_usd
echo $cexio | tr '#' '\n' | grep usd
echo $coinmarketcap | tr '#' '\n' | grep usd

echo $hitbtc  | tr '#' '\n' | grep usd
echo $kraken | tr '#' '\n' | grep usd

echo multigraph bch_cny

curl -m 10 -L -s 'http://api.chbtc.com/data/v1/ticker?currency=bcc_cny' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("chbtc_cny.value " + j["ticker"]["last"])
except:
 pass'

echo $coinmarketcap | tr '#' '\n' | grep cny

