#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_fee - Plugin to monitor bicoin daemon.

=head1 CONFIGURATION

Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.

=head1 NOTES

Uses the command "bitcoin-cli"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ -e $MUNIN_LIBDIR/plugins/plugin.sh ]; then
	. $MUNIN_LIBDIR/plugins/plugin.sh
fi

if [ "$1" = "autoconf" ]; then
	if ( bitcoin-cli -datadir=$BITCOIN_DATADIR getdifficulty >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"bitcoin-cli\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind blocks'
	echo 'graph_args --base 1000'
	echo 'graph_scale no'
	echo 'graph_vlabel blocks per hour'
	echo 'graph_category bitcoind'
	echo 'blocks.label blocks'
	echo 'blocks.type DERIVE'
	echo 'blocks.cdef blocks,3600,*'
	exit 0
fi

TFILE=/tmp/munin-bitcoin-blocks-$$
/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR getblockchaininfo > $TFILE

echo "blocks.value `grep blocks $TFILE | grep -o '[0-9\.]*'`"

rm $TFILE
