#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_diff - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/bitcoin.
Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.
Edit the BITCOIN_CLI setting to specify the location of bitcoin-cli.

=head1 NOTES

Uses env.BITCOIN_CLI and env.BITCOIN_DATADIR in /etc/munin/plugin-conf.d/bitcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind difficulty'
	echo 'graph_args --base 1000 --logarithmic'
	echo 'graph_vlabel value'
	echo 'graph_category bitcoind'
	echo 'difficulty.label difficulty'
	echo 'difficulty.type GAUGE'
	exit 0
fi

TFILE=/tmp/munin-bitcoin-diff-$$
${BITCOIN_CLI} -datadir=$BITCOIN_DATADIR getdifficulty > $TFILE

echo "difficulty.value `cat $TFILE`"

rm $TFILE
