#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_mp - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/bitcoin.
Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.
Edit the BITCOIN_CLI setting to specify the location of bitcoin-cli.

=head1 NOTES

Uses env.BITCOIN_CLI and env.BITCOIN_DATADIR in /etc/munin/plugin-conf.d/bitcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind memory pool'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category bitcoind'
	echo 'size.label size'
	echo 'size.type GAUGE'
	echo 'size.max 1000000'
	exit 0
fi

# ${BITCOIN_CLI} getmempoolinfo
#{
#  "size": 11853,
#  "bytes": 45560692,
#  "usage": 89999136,
#  "maxmempool": 300000000,
#  "mempoolminfee": 0.00000000
#}

TFILE=/tmp/munin-bitcoin-mp-$$
${BITCOIN_CLI} -datadir=$BITCOIN_DATADIR getmempoolinfo > $TFILE

echo "size.value `grep size $TFILE | grep -o '[0-9]*'`"

rm $TFILE
