#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_vm - Plugin to monitor bicoin daemon.

=head1 CONFIGURATION

Edit the -datadir parameter to specify the location of your bitcoin data directory.

=head1 NOTES

Uses the command "bitcoin-cli"

=head1 AUTHOR

hsmiths

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if ( bitcoin-cli -datadir=/home/shsmith/.bitcoin getinfo >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"bitcoin-cli\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind process memory'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
    echo 'graph_scale no'
	echo 'graph_category bitcoind'
    echo 'vmsize.label VmSize'
    echo 'vmsize.type GAUGE'
    echo 'vmrss.label VmRss'
    echo 'vmrss.type GAUGE'
    echo 'vmswap.label VmSwap'
    echo 'vmswap.type GAUGE'
	exit 0
fi

pid=`pidof bitcoind`
echo "vmsize.value `grep VmSize /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmrss.value `grep VmRSS /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmswap.value `grep VmSwap /proc/$pid/status | grep -o '[0-9]*'`"

exit 0

