#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_fee - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.

=head1 NOTES

Uses the command "bitcoin-cli"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if ( bitcoin-cli -datadir=$BITCOIN_DATADIR getdifficulty >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"bitcoin-cli\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind fees'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel satoshi/byte'
	echo 'graph_category bitcoind'
	echo 'relayfee.label relayfee'
	echo 'relayfee.type GAUGE'
	echo 'mempoolminfee.label mempoolminfee'
	echo 'mempoolminfee.type GAUGE'
	echo 'mempoolminfee.cdef mempoolminfee,97656,*'
	echo 'estimatesmartfee1.label estimatesmartfee 1 block'
	echo 'estimatesmartfee1.type GAUGE'
	echo 'estimatesmartfee1.min 0'
	echo 'estimatesmartfee1.cdef estimatesmartfee1,97656,*'
	echo 'estimatesmartfee2.label estimatesmartfee 2 blocks'
	echo 'estimatesmartfee2.type GAUGE'
	echo 'estimatesmartfee2.min 0'
	echo 'estimatesmartfee2.cdef estimatesmartfee2,97656,*'
	echo 'estimatesmartfee3.label estimatesmartfee 3 blocks'
	echo 'estimatesmartfee3.type GAUGE'
	echo 'estimatesmartfee3.min 0'
	echo 'estimatesmartfee3.cdef estimatesmartfee3,97656,*'
	echo 'estimatesmartfee4.label estimatesmartfee 4 blocks'
	echo 'estimatesmartfee4.type GAUGE'
	echo 'estimatesmartfee4.min 0'
	echo 'estimatesmartfee4.cdef estimatesmartfee4,97656,*'
	echo 'estimatesmartfee5.label estimatesmartfee 5 blocks'
	echo 'estimatesmartfee5.type GAUGE'
	echo 'estimatesmartfee5.min 0'
	echo 'estimatesmartfee5.cdef estimatesmartfee5,97656,*'
	echo 'estimatesmartfee10.label estimatesmartfee 10 blocks'
	echo 'estimatesmartfee10.type GAUGE'
	echo 'estimatesmartfee10.min 0'
	echo 'estimatesmartfee10.cdef estimatesmartfee10,97656,*'
	echo 'estimatesmartfee20.label estimatesmartfee 20 blocks'
	echo 'estimatesmartfee20.type GAUGE'
	echo 'estimatesmartfee20.min 0'
	echo 'estimatesmartfee20.cdef estimatesmartfee20,97656,*'
	exit 0
fi

TFILE=/tmp/munin-bitcoin-fee-$$
/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR getnetworkinfo > $TFILE
echo "relayfee.value `grep relayfee $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR getmempoolinfo > $TFILE
echo "mempoolminfee.value `grep mempoolminfee $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR estimatesmartfee 1 > $TFILE
echo "estimatesmartfee1.value `grep feerate $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR estimatesmartfee 2 > $TFILE
echo "estimatesmartfee2.value `grep feerate $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR estimatesmartfee 3 > $TFILE
echo "estimatesmartfee3.value `grep feerate $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR estimatesmartfee 4 > $TFILE
echo "estimatesmartfee4.value `grep feerate $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR estimatesmartfee 5 > $TFILE
echo "estimatesmartfee5.value `grep feerate $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR estimatesmartfee 10 > $TFILE
echo "estimatesmartfee10.value `grep feerate $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR estimatesmartfee 20 > $TFILE
echo "estimatesmartfee20.value `grep feerate $TFILE | grep -o '[0-9\.]*'`"

rm $TFILE
