#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_ticker - Plugin to monitor bitcoin tickers.

=head1 CONFIGURATION

=head1 NOTES

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoin tickers - usd'
	echo 'graph_args --base 1000'
	echo 'graph_scale no'
	echo 'graph_vlabel USD'
	echo 'graph_category bitcoind'
	echo 'bitcoinaverage.label bitcoinaverage.com'
	echo 'blockchain.label blockchain.info'
	#echo 'btce.label btc-e.com'
	echo 'cexio.label cex.io'
	echo 'coinbase.label coinbase.com (gdax)'
	echo 'coindesk.label coindesk.com'
	echo 'coinmarketcap.label coinmarketcap.com'
	echo 'gemini.label gemini.com'
	echo 'kraken.label kraken.com'
	echo 'winkdex.label winkdex.com'
	exit 0
fi

curl -m 10 -L -s 'apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("bitcoinaverage.value " + str(j["last"]))
except:
 pass'

curl -m 10 -s 'blockchain.info/ticker' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("blockchain.value " + str(j["USD"]["last"]))
except:
 pass'

#curl -m 10 -L -s 'btc-e.com/api/3/ticker/btc_usd' | python3 -c '
#import sys, json
#try:
# j=json.load(sys.stdin); print("btce.value " + str(j["btc_usd"]["last"]))
#except:
# pass'

curl -m 10 -L -s 'api.gdax.com/products/BTC-USD/ticker' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("coinbase.value " + str(j["price"]))
except:
 pass'

curl -m 10 -L -s 'https://cex.io/api/last_price/BTC/USD' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("cexio.value " + str(j["lprice"]))
except:
 pass'

curl -m 10 -L -s 'api.coindesk.com/v1/bpi/currentprice.json' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("coindesk.value " + str(j["bpi"]["USD"]["rate_float"]))
except:
 pass'

curl -m 10 -L -s 'https://api.coinmarketcap.com/v1/ticker/bitcoin' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("coinmarketcap.value " + str(j[0]["price_usd"]))
except:
 pass'

curl -m 10 -L -s 'https://api.gemini.com/v1/pubticker/BTCUSD' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("gemini.value " + str(j["last"]))
except:
 pass'

curl -m 10 -L -s 'https://api.kraken.com/0/public/Ticker?pair=XBTUSD' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("kraken.value " + str(j["result"]["XXBTZUSD"]["c"][0]))
except:
 pass'

curl -m 10 -L -s 'http://winkdex.com/api/v0/price' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); print("winkdex.value " + str(float(j["price"])/100))
except:
 pass'
