#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_mp - Plugin to monitor bicoin daemon.

=head1 CONFIGURATION

Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.

=head1 NOTES

Uses the command "bitcoin-cli"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BITCOIN_DATADIR=/home/shsmith/.bitcoin

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if ( bitcoin-cli -datadir=$BITCOIN_DATADIR getinfo >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"bitcoin-cli\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind memory pool'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category bitcoind'
	echo 'size.label size'
	echo 'size.type GAUGE'
	echo 'size.max 1000000'
	exit 0
fi

# bitcoin-cli getmempoolinfo
#{
#  "size": 11853,
#  "bytes": 45560692,
#  "usage": 89999136,
#  "maxmempool": 300000000,
#  "mempoolminfee": 0.00000000
#}

TFILE=/tmp/munin-bitcoin-mp-$$
/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR getmempoolinfo > $TFILE

echo "size.value `grep size $TFILE | grep -o '[0-9]*'`"

rm $TFILE
