#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_fee - Plugin to monitor bicoin daemon.

=head1 CONFIGURATION

Edit the -datadir parameter to specify the location of your bitcoin data directory.

=head1 NOTES

Uses the command "bitcoin-cli"

=head1 AUTHOR

hsmiths

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if ( bitcoin-cli -datadir=/home/shsmith/.bitcoin getinfo >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"bitcoin-cli\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind fees'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category bitcoind'
	echo 'paytxfee.label paytxfee'
	echo 'paytxfee.type GAUGE'
	echo 'paytxfee.max 1'
	echo 'relayfee.label relayfee'
	echo 'relayfee.type GAUGE'
	echo 'relayfee.max 1'
	echo 'mempoolminfee.label mempoolminfee'
	echo 'mempoolminfee.type GAUGE'
	echo 'mempoolminfee.max 1'
	exit 0
fi

#bitcoin-cli getinfo
#{
#  "version": 130100,
#  "protocolversion": 70014,
#  "blocks": 445876,
#  "timeoffset": 0,
#  "connections": 27,
#  "proxy": "",
#  "difficulty": 317688400354.0338,
#  "testnet": false,
#  "paytxfee": 0.00000000,
#  "relayfee": 0.00001000,
#  "errors": ""
#}
#bitcoin-cli getmempoolinfo
#{
#  "size": 9512,
#  "bytes": 46029357,
#  "usage": 89112336,
#  "maxmempool": 300000000,
#  "mempoolminfee": 0.00000000
#}

TFILE=/tmp/munin-bitcoin-fee
/usr/bin/bitcoin-cli -datadir=/home/shsmith/.bitcoin getinfo > $TFILE

echo "paytxfee.value `grep paytxfee $TFILE | grep -o '[0-9\.]*'`"
echo "relayfee.value `grep relayfee $TFILE | grep -o '[0-9\.]*'`"

/usr/bin/bitcoin-cli -datadir=/home/shsmith/.bitcoin getmempoolinfo > $TFILE

echo "mempoolminfee.value `grep mempoolminfee $TFILE | grep -o '[0-9\.]*'`"

rm $TFILE
