#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_blocks - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/bitcoin.
Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.
Edit the BITCOIN_CLI setting to specify the location of bitcoin-cli.

=head1 NOTES

Uses env.BITCOIN_CLI and env.BITCOIN_DATADIR in /etc/munin/plugin-conf.d/bitcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind blocks'
	echo 'graph_args --base 1000'
	echo 'graph_scale no'
	echo 'graph_vlabel blocks per hour'
	echo 'graph_category bitcoind'
	echo 'blocks.label blocks'
	echo 'blocks.type DERIVE'
	echo 'blocks.cdef blocks,3600,*'
	exit 0
fi

TFILE=/tmp/munin-bitcoin-blocks-$$
${BITCOIN_CLI} -datadir=$BITCOIN_DATADIR getblockchaininfo > $TFILE

echo "blocks.value `grep blocks $TFILE | grep -o '[0-9\.]*'`"

rm $TFILE
