#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_bw - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/bitcoin.
Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.
Edit the BITCOIN_CLI setting to specify the location of bitcoin-cli.

=head1 NOTES

Uses env.BITCOIN_CLI and env.BITCOIN_DATADIR in /etc/munin/plugin-conf.d/bitcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind bandwidth'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel bytes per ${graph_period} recv (-) / sent (+)'
	echo 'graph_category bitcoind'
	echo 'bytesrecv.label bytes received'
	echo 'bytesrecv.type DERIVE'
	echo 'bytesrecv.min 0'
	echo 'bytesrecv.graph no'
	echo 'bytessent.label bytes'
	echo 'bytessent.type DERIVE'
	echo 'bytessent.negative bytesrecv'
	echo 'bytessent.min 0'
	exit 0
fi

TFILE=/tmp/munin-bitcoin-bw-$$
${BITCOIN_CLI} -datadir=$BITCOIN_DATADIR getnettotals > $TFILE

echo "bytesrecv.value `grep totalbytesrecv $TFILE | grep -o '[0-9]*'`"
echo "bytessent.value `grep totalbytessent $TFILE | grep -o '[0-9]*'`"

rm $TFILE
