#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_con - Plugin to monitor bicoin daemon.

=head1 CONFIGURATION

Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.

=head1 NOTES

Uses the command "bitcoin-cli"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BITCOIN_DATADIR=/home/shsmith/.bitcoin

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if ( bitcoin-cli -datadir=$BITCOIN_DATADIR getdifficulty >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"bitcoin-cli\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind connections'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category bitcoind'
	echo 'connections.label Connections'
	echo 'connections.type GAUGE'
	echo 'connections.max 10000'
	exit 0
fi

TFILE=/tmp/munin-bitcoin-con-$$
/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR getnetworkinfo > $TFILE

echo "connections.value `grep connections $TFILE | grep -o '[0-9]*'`"

rm $TFILE
