#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_conn - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/bitcoin.
Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.
Edit the BITCOIN_CLI setting to specify the location of bitcoin-cli.

=head1 NOTES

Uses env.BITCOIN_CLI and env.BITCOIN_DATADIR in /etc/munin/plugin-conf.d/bitcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind connections'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel connections'
	echo 'graph_category bitcoind'
	echo 'connections.label Connections'
	echo 'connections.type GAUGE'
	echo 'connections.max 10000'
	exit 0
fi

TFILE=/tmp/munin-bitcoin-con-$$
${BITCOIN_CLI} -datadir=$BITCOIN_DATADIR getnetworkinfo > $TFILE

echo "connections.value `grep connections $TFILE | grep -o '[0-9]*'`"

rm $TFILE
