#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_ticker_bch - Plugin to monitor BCH tickers.

=head1 CONFIGURATION

No configuration.

=head1 NOTES

Uses python3.

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'multigraph bch_btc'
	echo 'graph_title BCH tickers - BTC'
	echo 'graph_args --base 1000'
	echo 'graph_vlabel BTC'
	echo 'graph_category bitcoind'
	echo 'bitcoinaverage_btc.label bitcoinaverage.com'
	echo 'cexio_btc.label cex.io'
	echo 'cexio_btc.max 10'
	echo 'coinbase_btc.label coinbase.com'
	echo 'coinbase_btc.max 100000'
	echo 'coinmarketcap_btc.label coinmarketcap.com'
	echo 'coinmarketcap_btc.max 10'
	echo 'hitbtc_btc.label hitbtc.com'
	echo 'hitbtc_btc.max 10'
	echo 'kraken_btc.label kraken.com'
	echo 'kraken_btc.max 10'
	echo 'shapeshift_btc.label shapeshift.io'
	echo 'shapeshift_btc.max 10'

	echo 'multigraph bch_usd'
	echo 'graph_title BCH tickers - USD'
	echo 'graph_args --base 1000'
	echo 'graph_scale no'
	echo 'graph_vlabel USD'
	echo 'graph_category bitcoind'
	echo 'bitcoinaverage_usd.label bitcoinaverage.com'
	echo 'cexio_usd.label cex.io'
	echo 'cexio_usd.max 10000'
	echo 'coinbase_usd.label coinbase.com'
	echo 'coinbase_usd.max 100000'
	echo 'coinmarketcap_usd.label coinmarketcap.com'
	echo 'coinmarketcap_usd.max 10000'
	echo 'hitbtc_usd.label hitbtc.com'
	echo 'hitbtc_usd.max 10000'
	echo 'kraken_usd.label kraken.com'
	echo 'kraken_usd.max 10000'

	echo 'multigraph bch_cny'
	echo 'graph_title BCH tickers - CNY'
	echo 'graph_args --base 1000'
	echo 'graph_scale no'
	echo 'graph_vlabel CNY'
	echo 'graph_category bitcoind'
	echo 'bitcoinaverage_cny.label bitcoinaverage.com'
	echo 'coinmarketcap_cny.label coinmarketcap.com'
	exit 0
fi

coinmarketcap=`curl -m 10 -L -s 'https://api.coinmarketcap.com/v1/ticker/bitcoin-cash/?convert=CNY' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("#coinmarketcap_btc.value " + j[0]["price_btc"])
 print("#coinmarketcap_usd.value " + j[0]["price_usd"])
 print("#coinmarketcap_cny.value " + j[0]["price_cny"])
except:
 pass'`

hitbtc=`curl -m 10 -L -s 'https://api.hitbtc.com/api/1/public/ticker' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("#hitbtc_btc.value " + str(j["BCHBTC"]["last"]))
 print("#hitbtc_usd.value " + str(j["BCHUSD"]["last"]))
except:
 pass'`

kraken=`curl -m 20 -L -s 'https://api.kraken.com/0/public/Ticker?pair=BCHUSD,BCHXBT' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("#kraken_usd.value " + str(j["result"]["BCHUSD"]["c"][0]))
 print("#kraken_btc.value " + str(j["result"]["BCHXBT"]["c"][0]))
except:
 pass'`

echo multigraph bch_btc

curl -m 10 -L -s 'https://apiv2.bitcoinaverage.com/indices/crypto/ticker/BCHBTC' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); p=j["last"]
 print("bitcoinaverage_btc.value " + str(p))
except:
 pass'

curl -m 10 -L -s 'https://api.pro.coinbase.com/products/BCH-BTC/ticker' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); p=j["price"]
 print("coinbase_btc.value " + str(p))
except:
 pass'

curl -m 10 -L -s 'https://cex.io/api/last_price/BCH/BTC' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("cexio_btc.value " + str(j["lprice"]))
except:
 pass'

echo $coinmarketcap | tr '#' '\n' | grep btc
echo $hitbtc  | tr '#' '\n' | grep _btc
echo $kraken | tr '#' '\n' | grep btc

curl -m 10 -L -s 'https://shapeshift.io/marketinfo/bch_btc' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("shapeshift_btc.value " + str(j["rate"]))
except:
 pass'

echo multigraph bch_usd

curl -m 10 -L -s 'https://apiv2.bitcoinaverage.com/indices/global/ticker/BCHUSD' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); p=j["last"]
 print("bitcoinaverage_usd.value " + str(p))
except:
 pass'

curl -m 10 -L -s 'https://cex.io/api/last_price/BCH/USD' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin)
 print("cexio_usd.value " + str(j["lprice"]))
except:
 pass'

curl -m 10 -L -s 'https://api.pro.coinbase.com/products/BCH-USD/ticker' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); p=j["price"]
 print("coinbase_usd.value " + str(p))
except:
 pass'

echo $coinmarketcap | tr '#' '\n' | grep usd
echo $hitbtc  | tr '#' '\n' | grep usd
echo $kraken | tr '#' '\n' | grep usd

echo multigraph bch_cny

curl -m 10 -L -s 'https://apiv2.bitcoinaverage.com/indices/global/ticker/BCHCNY' | python3 -c '
import sys, json
try:
 j=json.load(sys.stdin); p=j["last"]
 print("bitcoinaverage_cny.value " + str(p))
except:
 pass'

echo $coinmarketcap | tr '#' '\n' | grep cny
