#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_fee - Plugin to monitor bicoin daemon.

=head1 CONFIGURATION

Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.

=head1 NOTES

Uses the command "bitcoin-cli"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BITCOIN_DATADIR=/home/shsmith/.bitcoin

if [ -e $MUNIN_LIBDIR/plugins/plugin.sh ]; then
	. $MUNIN_LIBDIR/plugins/plugin.sh
fi

if [ "$1" = "autoconf" ]; then
	if ( bitcoin-cli -datadir=$BITCOIN_DATADIR getinfo >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"bitcoin-cli\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind difficulty'
	echo 'graph_args --base 1000 --logarithmic'
	echo 'graph_vlabel value'
	echo 'graph_category bitcoind'
	echo 'difficulty.label difficulty'
	echo 'difficulty.type GAUGE'
	exit 0
fi

#bitcoin-cli getinfo
#{
#  "version": 130100,
#  "protocolversion": 70014,
#  "blocks": 445876,
#  "timeoffset": 0,
#  "connections": 27,
#  "proxy": "",
#  "difficulty": 317688400354.0338,
#  "testnet": false,
#  "paytxfee": 0.00000000,
#  "relayfee": 0.00001000,
#  "errors": ""
#}

TFILE=/tmp/munin-bitcoin-diff-$$
/usr/bin/bitcoin-cli -datadir=$BITCOIN_DATADIR getinfo > $TFILE

echo "difficulty.value `grep difficulty $TFILE | grep -o '[0-9\.]*'`"

rm $TFILE
