#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_vm - Plugin to monitor bitcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/bitcoin.
Edit the BITCOIN_DATADIR setting to specify the location of your bitcoin data directory.
Edit the BITCOIN_CLI setting to specify the location of bitcoin-cli.

=head1 NOTES

Uses env.BITCOIN_CLI and env.BITCOIN_DATADIR in /etc/munin/plugin-conf.d/bitcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind process memory'
	echo 'graph_args --base 1024 -l 0'
	echo 'graph_vlabel bytes'
	echo 'graph_category bitcoind'
	echo 'vmsize.label VmSize'
	echo 'vmsize.type GAUGE'
	echo 'vmsize.cdef vmsize,1024,*'
	echo 'vmrss.label VmRss'
	echo 'vmrss.type GAUGE'
	echo 'vmrss.cdef vmrss,1024,*'
	echo 'vmswap.label VmSwap'
	echo 'vmswap.type GAUGE'
	echo 'vmswap.cdef vmswap,1024,*'
	exit 0
fi

pid=`pidof bitcoind`
if [ "$pid" = "" ]; then
	exit 0
fi
echo "vmsize.value `grep VmSize /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmrss.value `grep VmRSS /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmswap.value `grep VmSwap /proc/$pid/status | grep -o '[0-9]*'`"

exit 0

