#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

bitcoin_tx - Plugin to monitor bitcoin daemon.
report total transaction rate on the blockchain.

=head1 CONFIGURATION

Uses 'journalctl' to read the output of bitcoind. 
Substitute a different command line if you are not using systemd.

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title bitcoind transaction rate'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel transactions per second'
	echo 'graph_category bitcoind'
	echo 'tx.label total tx rate'
	echo 'tx.type DERIVE'
	echo 'tx.min 0'
	exit 0
fi

# extract the last tx count line and format into tx.value

echo "tx.value `${BITCOIN_CLI} -datadir=$BITCOIN_DATADIR getchaintxstats | grep txcount | grep -o '[0-9]*'`"
