#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

electrumx_users - Plugin to monitor ElectrumX server.

=head1 CONFIGURATION

No configuration

=head1 NOTES

Uses the command "electrumx_rpc.py"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ -e $MUNIN_LIBDIR/plugins/plugin.sh ]; then
	. $MUNIN_LIBDIR/plugins/plugin.sh
fi

if [ "$1" = "autoconf" ]; then
	if ( electrumx_rpc.py getinfo >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"electrumx_rpc.py\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ElectrumX Users'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category ElectrumX'
	echo 'sessions.label User Sessions'
	echo 'sessions.type GAUGE'
	echo 'peers.label Good Peers'
	echo 'peers.type GAUGE'
	echo 'tusers.label Total Users (estimated)'
	echo 'tusers.type GAUGE'
	exit 0
fi

TFILE=/tmp/munin-electrumx-users-$$
/usr/local/bin/electrumx_rpc.py getinfo > $TFILE

# each session is connected to 8 other peers
# so estimated total users is mySessions * goodPeers / connectionsPerUser
mySessions=`grep sessions $TFILE | grep -o '[0-9]*'`
goodPeers=`grep good $TFILE | grep -o '[0-9]*'`
totalUsers=`expr $mySessions "*" $goodPeers / 8`

echo "sessions.value $mySessions"
echo "peers.value $goodPeers"
echo "tusers.value $totalUsers"

rm $TFILE
