#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

electrumx_ses - Plugin to monitor ElectrumX server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/electrumx.
Edit the ELECTRUMX_RPC setting to specify the location of electrumx_rpc.py.

=head1 NOTES

Uses env.ELECTRUMX_RPC in /etc/munin/plugin-conf.d/electrumx

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ElectrumX Request Counts'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel per second'
	echo 'graph_category ElectrumX'
	echo 'blockchain_block_header.label blockchain.block.header'
	echo 'blockchain_block_header.type DERIVE'
	echo 'blockchain_block_header.min 0'
	echo 'blockchain_block_headers.label blockchain.block.headers'
	echo 'blockchain_block_headers.type DERIVE'
	echo 'blockchain_block_headers.min 0'
	echo 'blockchain_estimatefee.label blockchain.estimatefee'
	echo 'blockchain_estimatefee.type DERIVE'
	echo 'blockchain_estimatefee.min 0'
	echo 'blockchain_headers_subscribe.label blockchain.headers.subscribe'
	echo 'blockchain_headers_subscribe.type DERIVE'
	echo 'blockchain_headers_subscribe.min 0'
	echo 'blockchain_relayfee.label blockchain.relayfee'
	echo 'blockchain_relayfee.type DERIVE'
	echo 'blockchain_relayfee.min 0'
	echo 'blockchain_scripthash_get_history.label blockchain.scripthash.get_history'
	echo 'blockchain_scripthash_get_history.type DERIVE'
	echo 'blockchain_scripthash_get_history.min 0'
	echo 'blockchain_scripthash_listunspent.label blockchain.scripthash.listunspent'
	echo 'blockchain_scripthash_listunspent.type DERIVE'
	echo 'blockchain_scripthash_listunspent.min 0'
	echo 'blockchain_scripthash_subscribe.label blockchain.scripthash.subscribe'
	echo 'blockchain_scripthash_subscribe.type DERIVE'
	echo 'blockchain_scripthash_subscribe.min 0'
	echo 'blockchain_transaction_get.label blockchain.transaction.get'
	echo 'blockchain_transaction_get.type DERIVE'
	echo 'blockchain_transaction_get.min 0'
	echo 'blockchain_transaction_get_merkle.label blockchain.transaction.get_merkle'
	echo 'blockchain_transaction_get_merkle.type DERIVE'
	echo 'blockchain_transaction_get_merkle.min 0'
	echo 'disconnect.label disconnect'
	echo 'disconnect.type DERIVE'
	echo 'disconnect.min 0'
	echo 'getinfo.label getinfo'
	echo 'getinfo.type DERIVE'
	echo 'getinfo.min 0'
	echo 'mempool_get_fee_histogram.label mempool.get_fee_histogram'
	echo 'mempool_get_fee_histogram.type DERIVE'
	echo 'mempool_get_fee_histogram.min 0'
	echo 'peers.label peers'
	echo 'peers.type DERIVE'
	echo 'peers.min 0'
	echo 'server_banner.label server.banner'
	echo 'server_banner.type DERIVE'
	echo 'server_banner.min 0'
	echo 'server_donation_address.label server.donation_address'
	echo 'server_donation_address.type DERIVE'
	echo 'server_donation_address.min 0'
	echo 'server_peers_subscribe.label server.peers.subscribe'
	echo 'server_peers_subscribe.type DERIVE'
	echo 'server_peers_subscribe.min 0'
	echo 'server_ping.label server.ping'
	echo 'server_ping.type DERIVE'
	echo 'server_ping.min 0'
	echo 'server_version.label server.version'
	echo 'server_version.type DERIVE'
	echo 'server_version.min 0'
	echo 'sessions.label sessions'
	echo 'sessions.type DERIVE'
	echo 'sessions.min 0'

	exit 0
fi

#{
#    "coin": "BitcoinSegwit",
#    "daemon": "127.0.0.1:8332/",
#    "daemon height": 572877,
#    "db height": 572877,
#    "groups": 18,
#    "history cache": "592 lookups 57 hits 502 entries",
#    "merkle cache": "109 lookups 1 hits 108 entries",
#    "peers": {
#        "bad": 0,
#        "good": 0,
#        "never": 0,
#        "stale": 0,
#        "total": 0
#    },
#    "pid": 121656,
#    "request counts": {
#        "blockchain.block.header": 115,
#        "blockchain.block.headers": 56,
#        "blockchain.estimatefee": 1839,
#        "blockchain.headers.subscribe": 5377,
#        "blockchain.relayfee": 40,
#        "blockchain.scripthash.get_history": 30,
#        "blockchain.scripthash.listunspent": 11,
#        "blockchain.scripthash.subscribe": 562,
#        "blockchain.transaction.get": 28,
#        "blockchain.transaction.get_merkle": 109,
#        "disconnect": 7364,
#        "getinfo": 4618,
#        "mempool.get_fee_histogram": 460,
#        "peers": 866,
#        "server.banner": 41,
#        "server.donation_address": 52,
#        "server.peers.subscribe": 2,
#        "server.ping": 215,
#        "server.version": 7582,
#        "sessions": 12186
#    },
#    "request total": 41553,
#    "sessions": {
#        "count": 13,
#        "count with subs": 0,
#        "errors": 0,
#        "logged": 0,
#        "paused": 0,
#        "pending requests": 1,
#        "subs": 0
#    },
#    "tx hashes cache": "109 lookups 0 hits 108 entries",
#    "txs sent": 0,
#    "uptime": "18h 00m 27s",
#    "version": "ElectrumX 1.11.0"
#}

TFILE=/tmp/munin-electrumx-reqcounts-$$
${ELECTRUMX_RPC} getinfo > $TFILE

echo blockchain_block_header.value `grep \\"blockchain.block.header\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_block_headers.value `grep \\"blockchain.block.headers\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_estimatefee.value `grep \\"blockchain.estimatefee\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_headers_subscribe.value `grep \\"blockchain.headers.subscribe\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_relayfee.value `grep \\"blockchain.relayfee\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_scripthash_get_history.value `grep \\"blockchain.scripthash.get_history\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_scripthash_listunspent.value `grep \\"blockchain.scripthash.listunspent\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_scripthash_subscribe.value `grep \\"blockchain.scripthash.subscribe\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_transaction_get.value `grep \\"blockchain.transaction.get\\" $TFILE | grep -o '[0-9]*'`
echo blockchain_transaction_get_merkle.value `grep \\"blockchain.transaction.get.merkle\\" $TFILE | grep -o '[0-9]*'`
echo disconnect.value `grep \\"disconnect\\" $TFILE | grep -o '[0-9]*'`
echo getinfo.value `grep \\"getinfo\\" $TFILE | grep -o '[0-9]*'`
echo mempool_get_fee_histogram.value `grep \\"mempool.get.fee.histogram\\" $TFILE | grep -o '[0-9]*'`
echo peers.value `grep \\"peers\\" $TFILE | grep -o '[0-9]*'`
echo server_banner.value `grep \\"server.banner\\" $TFILE | grep -o '[0-9]*'`
echo server_donation_address.value `grep \\"server.donation.address\\" $TFILE | grep -o '[0-9]*'`
echo server_peers_subscribe.value `grep \\"server.peers.subscribe\\" $TFILE | grep -o '[0-9]*'`
echo server_ping.value `grep \\"server.ping\\" $TFILE | grep -o '[0-9]*'`
echo server_version.value `grep \\"server.version\\" $TFILE | grep -o '[0-9]*'`
echo sessions.value `grep \\"sessions\\" $TFILE | grep -o '[0-9]*'`

rm $TFILE
