#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

electrumx_sub - Plugin to monitor ElectrumX server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/electrumx.
Edit the ELECTRUMX_RPC setting to specify the location of electrumx_rpc.py.

=head1 NOTES

Uses env.ELECTRUMX_RPC in /etc/munin/plugin-conf.d/electrumx

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ElectrumX Subscriptions'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel count'
	echo 'graph_category ElectrumX'
	echo 'subs.label Subscriptions'
	echo 'subs.type GAUGE'
	echo 'subs.max 1000000'
	echo 'requests.label Requests'
	echo 'requests.type GAUGE'
	echo 'requests.max 10000'
	exit 0
fi

#{
#    "closing": 0,
#    "daemon_height": 443912,
#    "db_height": 443912,
#    "errors": 0,
#    "groups": 1,
#    "logged": 0,
#    "peers": 53,
#    "pid": 23142,
#    "requests": 0,
#    "sessions": 50,
#    "subs": 974,
#    "txs_sent": 1
#}

TFILE=/tmp/munin-electrumx-sub-$$
${ELECTRUMX_RPC} getinfo > $TFILE

echo "subs.value `grep subs $TFILE | grep -o '[0-9]*'`"
echo "requests.value `grep requests $TFILE | grep -o '[0-9]*'`"

rm $TFILE
