#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

electrumx_peers - Plugin to monitor ElectrumX server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/electrumx.
Edit the ELECTRUMX_RPC setting to specify the location of electrumx_rpc.py.

=head1 NOTES

Uses env.ELECTRUMX_RPC in /etc/munin/plugin-conf.d/electrumx

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ElectrumX Peers'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel peers'
	echo 'graph_category ElectrumX'
	echo 'bad.label Bad'
	echo 'bad.type GAUGE'
	echo 'current.label Current'
	echo 'current.type GAUGE'
	echo 'never.label Never'
	echo 'never.type GAUGE'
	echo 'stale.label Stale'
	echo 'stale.type GAUGE'
	echo 'blacklisted.label Blacklisted'
	echo 'blacklisted.type GAUGE'
	echo 'good.label Good'
	echo 'good.type GAUGE'
	echo 'peers.label Total'
	echo 'peers.type GAUGE'
	exit 0
fi

#{
#    "closing": 0,
#    "daemon": "sampc8:8332/",
#    "daemon_height": 453777,
#    "db_height": 453777,
#    "errors": 0,
#    "groups": 1,
#    "logged": 0,
#    "paused": 0,
#    "peers": {
#        "bad": 11,
#        "good": 54,
#        "never": 11,
#        "stale": 0,
#        "total": 76
#    },
#    "pid": 62669,
#    "requests": 0,
#    "sessions": 47,
#    "subs": 5840,
#    "txs_sent": 1,
#    "uptime": "02m 58s"
#}

TFILE=/tmp/munin-electrumx-peers-$$
${ELECTRUMX_RPC} getinfo > $TFILE

echo "bad.value `grep bad $TFILE | grep -o '[0-9]*'`"
CURRENT=`grep good $TFILE | grep -o '[0-9]*'`
echo "current.value $CURRENT"
echo "never.value `grep never $TFILE | grep -o '[0-9]*'`"
echo "stale.value `grep stale $TFILE | grep -o '[0-9]*'`"
echo "peers.value `grep total $TFILE | grep -o '[0-9]*'`"

BLACKLISTED=`${ELECTRUMX_RPC} peers | grep good | python3 -c '
import sys, json, requests
blacklist = json.loads(requests.get("https://electrum.org/blacklist.json").text)
for peer in sys.stdin:
        host = peer.split(" ",1)[0]
        if any(item in blacklist for item in (host, "*." + ".".join(host.split(".")[-2:]))):
                print(peer.rstrip())
' | wc -l`

echo "blacklisted.value $BLACKLISTED"
echo "good.value `expr $CURRENT - $BLACKLISTED`"

rm $TFILE
