#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

electrumx_peers - Plugin to monitor ElectrumX server.

=head1 CONFIGURATION

No configuration

=head1 NOTES

Uses the command "electrumx_rpc.py"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if ( electrumx_rpc.py getinfo >/dev/null 2>&1 ); then
		echo yes
		exit 0
	else
		if [ $? -eq 127 ]; then
			echo "no (could not run \"electrumx_rpc.py\")"
			exit 0
		else
			echo no
			exit 0
		fi
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ElectrumX Peers'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category ElectrumX'
	echo 'bad.label Bad'
	echo 'bad.type GAUGE'
	echo 'current.label Good'
	echo 'current.type GAUGE'
	echo 'never.label Never'
	echo 'never.type GAUGE'
	echo 'stale.label Stale'
	echo 'stale.type GAUGE'
	echo 'peers.label Total'
	echo 'peers.type GAUGE'
	exit 0
fi

#{
#    "closing": 0,
#    "daemon": "sampc8:8332/",
#    "daemon_height": 453777,
#    "db_height": 453777,
#    "errors": 0,
#    "groups": 1,
#    "logged": 0,
#    "paused": 0,
#    "peers": {
#        "bad": 11,
#        "good": 54,
#        "never": 11,
#        "stale": 0,
#        "total": 76
#    },
#    "pid": 62669,
#    "requests": 0,
#    "sessions": 47,
#    "subs": 5840,
#    "txs_sent": 1,
#    "uptime": "02m 58s"
#}

TFILE=/tmp/munin-electrumx-peers-$$
/usr/local/bin/electrumx_rpc.py getinfo > $TFILE

echo "bad.value `grep bad $TFILE | grep -o '[0-9]*'`"
echo "current.value `grep good $TFILE | grep -o '[0-9]*'`"
echo "never.value `grep never $TFILE | grep -o '[0-9]*'`"
echo "stale.value `grep stale $TFILE | grep -o '[0-9]*'`"
echo "peers.value `grep total $TFILE | grep -o '[0-9]*'`"

rm $TFILE
