#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

electrumx_mem - Plugin to monitor ElectrumX server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/electrumx.
Edit the ELECTRUMX_RPC setting to specify the location of electrumx_rpc.py.

=head1 NOTES

Uses env.ELECTRUMX_RPC in /etc/munin/plugin-conf.d/electrumx

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ElectrumX Memory'
	echo 'graph_args --base 1024 -l 0'
	echo 'graph_vlabel bytes'
	echo 'graph_category ElectrumX'
	echo 'vmsize.label VmSize'
	echo 'vmsize.type GAUGE'
	echo 'vmsize.cdef vmsize,1024,*'
	echo 'vmrss.label VmRss'
	echo 'vmrss.type GAUGE'
	echo 'vmrss.cdef vmrss,1024,*'
	echo 'vmswap.label VmSwap'
	echo 'vmswap.type GAUGE'
	echo 'vmswap.cdef vmswap,1024,*'
	exit 0
fi

#{
#    "closing": 0,
#    "daemon_height": 443912,
#    "db_height": 443912,
#    "errors": 0,
#    "groups": 1,
#    "logged": 0,
#    "peers": 53,
#    "pid": 23142,
#    "requests": 0,
#    "sessions": 50,
#    "subs": 974,
#    "txs_sent": 1
#}

TFILE=/tmp/munin-electrumx-mem-$$
${ELECTRUMX_RPC} getinfo > $TFILE

pid=`grep pid $TFILE | grep -o '[0-9]*'`

echo "vmsize.value `grep VmSize /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmrss.value `grep VmRSS /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmswap.value `grep VmSwap /proc/$pid/status | grep -o '[0-9]*'`"

rm $TFILE
