#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

electrumx_users - Plugin to monitor ElectrumX server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/electrumx.
Edit the ELECTRUMX_RPC setting to specify the location of electrumx_rpc.py.

=head1 NOTES

Uses env.ELECTRUMX_RPC in /etc/munin/plugin-conf.d/electrumx

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ElectrumX Users'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel count'
	echo 'graph_category ElectrumX'
	echo 'sessions.label User Sessions'
	echo 'sessions.type GAUGE'
	echo 'peers.label Good Peers'
	echo 'peers.type GAUGE'
	echo 'tusers.label Total Users (estimated)'
	echo 'tusers.type GAUGE'
	exit 0
fi

TFILE=/tmp/munin-electrumx-users-$$
${ELECTRUMX_RPC} getinfo > $TFILE

# each session is connected to 8 other peers
# so estimated total users is mySessions * goodPeers / connectionsPerUser
mySessions=`grep sessions $TFILE | grep -o '[0-9]*'`

currentPeers=`grep good $TFILE | grep -o '[0-9]*'`

blacklistedPeers=`${ELECTRUMX_RPC} peers | grep good | python3 -c '
import sys, json, requests
blacklist = json.loads(requests.get("https://electrum.org/blacklist.json").text)
for peer in sys.stdin:
        host = peer.split(" ",1)[0]
        if any(item in blacklist for item in (host, "*." + ".".join(host.split(".")[-2:]))):
                print(peer.rstrip())
' | wc -l`

goodPeers=`expr $currentPeers - $blacklistedPeers`
totalUsers=`expr $mySessions "*" $goodPeers / 8`

echo "sessions.value $mySessions"
echo "peers.value $goodPeers"
echo "tusers.value $totalUsers"

rm $TFILE
